### PR TITLE
Add DbSchema

### PR DESCRIPTION
**Pull request by dkapitan**
# Requirements for your pull request
- I have read and understood the contribution.MD file

### CODE REVIEW

**Comment by mgramin** [comment]
Thanks a ton for your PR! Is this project alive? I have noticed "2019" on the site.

**Comment by dkapitan** [comment]
I think it is still active. Have purchased a license last year and quite happy with it.

**Comment by mgramin** [comment]
I am very grateful to you! It seems to me that the last sentence is duplicated. Could you fix it?

**Comment by mgramin** [comment]
Thanks a million for your contribution!

**Pull request merged**
