### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RjPatil27**
# Requirements for your pull request
- I have read and understood the contribution.MD file
- Issue #199 resolved

### CODE REVIEW

**Comment by RjPatil27** [comment]
Issue #199 resolved

**Comment by mgramin** [comment]
Hi, thanks for your PR. Please put new item in alphabetical order in the current category and remove trailing slash in link (according to the [contributing rules](https://github.com/mgramin/awesome-db-tools/blob/master/contributing.md))

**Review by RjPatil27 — COMMENTED** [review]
Issue resolved.

**Comment by mgramin** [comment]
Thanks for your fix. Pay attention to the fourth paragraph of the contribution rules. If possible please use the github link https://github.com/slashbase/slashbase

**Comment by RjPatil27** [comment]
fixed

**Comment by mgramin** [comment]
Thanks for your PR.

**Pull request merged**
