### PR TITLE
add `pgTap` to testing section

### PR DESCRIPTION
**Pull request by pau4o**
# Requirements for your pull request
- [x] I have read and understood the contribution.MD file

### CODE REVIEW

**Comment by mgramin** [comment]
Thank you for your contribution @pau4o !

According to item number 4 of the [contributing reference](https://github.com/mgramin/awesome-db-tools/blob/master/contributing.md), GitHub links have priority. Since `pgtab` has a GitHub page, could you please use this link - https://github.com/theory/pgtap

**Comment by pau4o** [comment]
Consider it done.

**Comment by pau4o** [comment]
Is it problematic that I change commit and force pushed it?

**Comment by mgramin** [comment]
Thank you!

**Pull request merged**
