### PR TITLE
Add WebDB

### PR DESCRIPTION
**Pull request by aleluff**
# Requirements for your pull request
- I have read and understood the contribution.MD file

### CODE REVIEW

**Comment by mgramin** [comment]
Thank you for your contribution.

It would be beneficial to enhance the current description by adding more differentiating factors compared to other IDEs.

**Comment by mgramin** [comment]
@aleluff Thank you for your PR! Please fix the linter error:

```
README.md:87:2[9](https://github.com/mgramin/awesome-db-tools/actions/runs/6676891285/job/18184851251?pr=408#step:3:10)
  ✖  87:29  List item description must end with proper punctuation  remark-lint:awesome-list-item
```

**Comment by aleluff** [comment]
Done

**Comment by aleluff** [comment]
Hey,

Can you merge the PR please

**Comment by mgramin** [comment]
> Hey,
> 
> Can you merge the PR please

Hi @aleluff ! Sure, could you please provide your response to my previous comment - https://github.com/mgramin/awesome-db-tools/pull/408#issuecomment-1785210844 ?

**Comment by aleluff** [comment]
I didn't saw it, done

**Comment by mgramin** [comment]
Thank you @aleluff ! The updated description looks awesome! Could you please fix the linter error and I will merge it without delay

**Comment by aleluff** [comment]
Finally done

**Comment by mgramin** [comment]
Merged!😉

**Comment by aleluff** [comment]
Damm =)

Can you please take minutes to try and give me feedback

**Comment by mgramin** [comment]
@aleluff, sure, could you please provide me with your email or another contact method where I can leave my feedback?

**Comment by aleluff** [comment]
Here is my personal : aleluff@gmail.com

**Comment by aleluff** [comment]
I'm available for a call if you prefer

**Pull request merged**
