### PR TITLE
add ChartDB to Diagrams section

### PR DESCRIPTION
**Pull request by johnnyfish**
# Requirements for your pull request
- I have read and understood the contribution.MD file
- [ChartDB website](https://chartdb.io/) but in the README.md I linked to the Github project.

@mgramin Thank you! 🙂

### CODE REVIEW

**Review by Technetium1 — APPROVED** [review]
Good addition

**Comment by johnnyfish** [comment]
> Good addition

Thank you for the PR approval @Technetium1 
Can you merge the PR?

**Comment by Technetium1** [comment]
Nope. Would if I could.

**Comment by mgramin** [comment]
@johnnyfish @Technetium1 thank you for your contribution

**Comment by johnnyfish** [comment]
> @johnnyfish @Technetium1 thank you for your contribution

Thank you @mgramin 🏄

**Pull request merged**
