### PR TITLE
Add PostGraphile

### PR DESCRIPTION
**Pull request by ushieru**
PostGraphile Instant GraphQL API.

Instantly spin-up a GraphQL API server by pointing PostGraphile at your existing PostgreSQL database.

# Requirements for your pull request
- I have read and understood the contribution.MD file

### CODE REVIEW

**Comment by ushieru** [comment]
I'll fix missing dot. Sorry

**Comment by mgramin** [comment]
Hi @ushieru ! Thank you for your contribution. Could you please use github link (https://github.com/graphile/postgraphile), as per item four from contribution.md file?

**Comment by ushieru** [comment]
@mgramin of course, it's already.

**Comment by mgramin** [comment]
Thanks for your PR

**Pull request merged**
