### PR TITLE
replication: add data-diff for checking replication

### PR DESCRIPTION
**Pull request by sirupsen**
Adding [data-diff](https://github.com/datafold/data-diff) which uses an n-way binary search with checksums to check if two tables are the same, and prints out differences

### CODE REVIEW

**Comment by mgramin** [comment]
Thanks a lot for your contribution! How about create new subsection "Compare" in "Data" section and put in `data-diff` to this new section?

**Comment by sirupsen** [comment]
@mgramin no problem! Rebased and pushed

**Comment by mgramin** [comment]
Thank you. Could you fix the linter error, please?

**Comment by sirupsen** [comment]
@mgramin here you go! I don't have permission to run the workflow, but I ran `awesome-lint` locally and it passes!

**Comment by mgramin** [comment]
Thank you ;)

**Pull request merged**
